table 'Summed Process Report'
	lineageTag: e8d6bd19-9f12-4871-b865-7db356ebaa04

	measure 'Unpaid Time Mins' = CALCULATE(SUM('Summed Process Report'[total_mins]),FILTER('Summed Process Report','Summed Process Report'[labor_type]="UNP"),FILTER('Clock In Clock Out','Clock In Clock Out'[Shipping Flag]="Yes"))
		lineageTag: b108880d-ef61-4269-b7f6-1565962a6973

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SAM Mins' = CALCULATE(SUM('Summed Process Report'[Total_SAM_MINS]),FILTER('Summed Process Report','Summed Process Report'[labor_type]="DIR"),FILTER('Clock In Clock Out','Clock In Clock Out'[Shipping Flag]="Yes"))
		lineageTag: 1ac6b2f0-0dd3-4aff-961a-c6661de6f9fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Non Performance Time Mins' = CALCULATE(SUM('Summed Process Report'[total_mins]),FILTER('Summed Process Report','Summed Process Report'[labor_type]="NOP"),FILTER('Clock In Clock Out','Clock In Clock Out'[Shipping Flag]="Yes"))
		lineageTag: b9788251-0369-419b-aee9-cba057203b29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lunch Mins for lost time calc' = CALCULATE(SUM('Summed Process Report'[total_mins]),FILTER('Summed Process Report','Summed Process Report'[labor_type]="UNP"),FILTER('Summed Process Report','Summed Process Report'[Flag]="No"),FILTER('Clock In Clock Out','Clock In Clock Out'[Shipping Flag]="Yes"))
		lineageTag: cd076417-381c-4cf0-a291-b94adcaf863e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lunch Mins' = CALCULATE(SUM('Summed Process Report'[total_mins]),FILTER('Summed Process Report','Summed Process Report'[labor_type]="UNP"),FILTER('Summed Process Report','Summed Process Report'[Flag]="No"))
		lineageTag: 1224d440-d5f0-4ee1-bec6-b1403007090c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Indirect Time Mins' = CALCULATE(SUM('Summed Process Report'[total_mins]),FILTER('Summed Process Report','Summed Process Report'[labor_type]="IND"),FILTER('Clock In Clock Out','Clock In Clock Out'[Shipping Flag]="Yes"))
		lineageTag: c73c5c34-dbbd-487b-868a-bf65fe80320c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Direct Time Mins' = CALCULATE(SUM('Summed Process Report'[total_mins]),FILTER('Summed Process Report','Summed Process Report'[labor_type]="DIR"),FILTER('Clock In Clock Out','Clock In Clock Out'[Shipping Flag]="Yes"))
		lineageTag: ee041daa-aafb-4aaf-a78f-dea222478e79

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Overall TTIW all' = IF([TTIW minutes]<300,[TTIW minutes]-[Lunch Mins],[TTIW minutes])
		lineageTag: 25c33a21-2a69-484e-b3cb-3c7eafafd476

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lost Time Mins' = if (([Overall TTIW for lost time calc]-[Direct Time Mins]-[Non Performance Time Mins]-[Indirect Time Mins])=[Overall TTIW all],BLANK(),[Overall TTIW for lost time calc]-[Direct Time Mins]-[Non Performance Time Mins]-[Indirect Time Mins])
		lineageTag: a0adad15-d2d3-4d16-b21e-1a1f0b271d4e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Direct %' = [Direct Time Mins]/[Overall TTIW all]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e0f94531-0a2a-4df2-9ce1-2eba50151f91

	measure 'Eff %' = AVERAGEX(VALUES('Clock In Clock Out'[Employee Name]),[SAM Mins]/[Direct Time Mins])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 30bcd944-2f9e-4e3c-96ae-df380a2672b9

	measure 'Indirect %' = [Indirect Time Mins]/[Overall TTIW all]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 537c0580-4252-42fd-9ee4-29c8c287f0e9

	measure 'Lost %' = [Lost Time Mins]/[Overall TTIW all]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: a0de6c0f-5302-4764-a11c-9f8d3f258637

	measure 'Perf %' = ([SAM Mins]+[Lost Time Mins]+[Indirect Time Mins]+[Non Performance Time Mins])/[Overall TTIW all]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 23cfc740-380d-4a62-b653-945c6c1e4f10

	measure 'Hours Worked' = [Overall TTIW all]/60
		lineageTag: 5e45a503-cbaa-4346-83b5-91bc72264d07

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Break Log Ins' = CALCULATE(COUNT('Summed Process Report'[total_transactions]),FILTER('Summed Process Report','Summed Process Report'[process_id]="43"))
		formatString: 0
		lineageTag: f8a5e95c-0051-46c2-9856-aae6aa5e9969

	measure 'Lunch Log Ins' = CALCULATE(COUNT('Summed Process Report'[total_transactions]),FILTER('Summed Process Report','Summed Process Report'[process_id]="45"))
		formatString: 0
		lineageTag: e7e55ea1-b203-457e-ad03-e48d1ef99176

	measure 'Overall TTIW for lost time calc' = IF([TTIW for lost time calc]<300,[TTIW for lost time calc]-[Lunch Minutes for lost time calc],[TTIW for lost time calc])
		lineageTag: 8cb392e2-2631-4a20-a687-a98421fbc892

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lunch Minutes for lost time calc' = CALCULATE(SUM('Summed Process Report'[total_mins]),FILTER('Summed Process Report','Summed Process Report'[labor_type]="UNP"),FILTER('Summed Process Report','Summed Process Report'[Flag]="No"),FILTER('Clock In Clock Out','Clock In Clock Out'[Shipping Flag]="Yes"))
		lineageTag: f674950c-058e-46b0-bdd2-ffc6fde64639

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Log On Minutes' = CALCULATE(SUM('Summed Process Report'[total_mins]),FILTER('Summed Process Report','Summed Process Report'[process_code]="LOG ON"))
		formatString: 0.0
		lineageTag: 5c76d3ad-9dc1-4148-a8e1-f3e24482e9fe

	measure 'Main Menu Minutes' = CALCULATE(SUM('Summed Process Report'[total_mins]),FILTER('Summed Process Report','Summed Process Report'[process_code]="MENU"))
		formatString: 0.0
		lineageTag: 0b109570-ac53-4215-a074-da83f4ada288

	measure 'Log On Transactions' = CALCULATE(SUM('Summed Process Report'[total_transactions]),FILTER('Summed Process Report','Summed Process Report'[process_code]="LOG ON"))
		formatString: 0
		lineageTag: 5fb42576-f39c-4af4-aba5-7360fdfd3d9c

	measure 'Main Menu Transactions' = CALCULATE(SUM('Summed Process Report'[total_transactions]),FILTER('Summed Process Report','Summed Process Report'[process_code]="MENU"))
		formatString: 0
		lineageTag: 05486667-321e-43cc-ab6b-9b923fc8d18a

	measure 'Perf % for overall' = ([SAM Mins]+[Lost Time Mins]+[Indirect Time Mins]+[Non Performance Time Mins])/CALCULATE(SUM('Clock In Clock Out'[Final TTIW]),FILTER('Clock In Clock Out','Clock In Clock Out'[Shipping Flag]="Yes"))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 36ac1197-9f8f-4a4e-9198-9a9ac0180818

	measure 'Direct % for overall' = [Direct Time Mins]/CALCULATE(SUM('Clock In Clock Out'[Final TTIW]),FILTER('Clock In Clock Out','Clock In Clock Out'[Shipping Flag]="Yes"))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 251f37f3-e4e0-41b3-b97d-f5b6a27d9bc9

	measure 'Lost % for overall' = [Lost Time Mins]/CALCULATE(SUM('Clock In Clock Out'[Final TTIW]),FILTER('Clock In Clock Out','Clock In Clock Out'[Shipping Flag]="Yes"))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 5c0f8ea9-4e03-481e-9eeb-ab1ff432d499

	measure 'Indirect % for overall' = [Indirect Time Mins]/CALCULATE(SUM('Clock In Clock Out'[Final TTIW]),FILTER('Clock In Clock Out','Clock In Clock Out'[Shipping Flag]="Yes"))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 4f1425ca-dc49-4beb-a5d5-df8b819d25b6

	measure 'Perf % Final' = AVERAGEX(VALUES('Clock In Clock Out'[Employee Name]),'Summed Process Report'[Perf % for overall])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: c216695d-da73-4419-bd47-61e657c8574d

	measure 'Direct Time % Final' = AVERAGEX(VALUES('Clock In Clock Out'[Employee Name]),'Summed Process Report'[Direct % for overall])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 18b26ab5-694c-4350-a469-fbe89e06df8e

	measure 'Indirect Time % Final' = AVERAGEX(VALUES('Clock In Clock Out'[Employee Name]),'Summed Process Report'[Indirect % for overall])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 69d7a8fc-be0e-4c17-bf9e-4d4b6fb18f8e

	measure 'Lost Time % Final' = AVERAGEX(VALUES('Clock In Clock Out'[Employee Name]),'Summed Process Report'[Lost % for overall])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 5561812b-e231-4a72-8ba5-f0b19fc845d7

	measure 'Perf % Final Weekly' = AVERAGEX(VALUES('Clock In Clock Out'[Work Day]),'Summed Process Report'[Perf % Final])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 5b69421a-39a7-4593-a714-aa26a11b0f78

	measure 'Eff % Weekly' = AVERAGEX(VALUES('Clock In Clock Out'[Work Day]),[Eff %])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: f360b12b-5443-4099-8ab0-87c89bb8f11f

	measure 'Direct Time % Weekly' = AVERAGEX(VALUES('Clock In Clock Out'[Work Day]),[Direct Time % Final])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 6d3bdbc9-48f8-4448-a39b-65011e56fb03

	measure 'Indirect Time % Weekly' = AVERAGEX(VALUES('Clock In Clock Out'[Work Day]),[Indirect Time % Final])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 6856dcf3-e765-4ba2-b261-349cb98d93a6

	measure 'Lost Time % Weekly' = AVERAGEX(VALUES('Clock In Clock Out'[Work Day]),[Lost Time % Final])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 741544d6-b743-4d83-bce9-15e3fd3ae804

	measure 'hours worked by emp' = SUMX(VALUES('Clock In Clock Out'[Employee Name]),[Hours Worked])
		lineageTag: 45e023cb-3548-4cfc-a12d-03eb49645397

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hours Worked Weekly' = SUMX(VALUES('Clock In Clock Out'[Work Day]),[hours worked by emp])
		lineageTag: 75582eef-7905-4336-a53d-c29448133721

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Break Hours' = (CALCULATE(SUM('Summed Process Report'[total_mins]),FILTER('Summed Process Report','Summed Process Report'[process_code]="BREAK"))/60)
		lineageTag: 7e42e89a-7217-4937-b861-5df3d82ce6f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lunch Hours' = (CALCULATE(SUM('Summed Process Report'[total_mins]),FILTER('Summed Process Report','Summed Process Report'[process_code]="LUNCH"))/60)
		lineageTag: 3dc22dac-e573-4f89-9169-717fb3d174a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lunch Over Hours' = (CALCULATE(SUM('Summed Process Report'[total_mins]),FILTER('Summed Process Report','Summed Process Report'[process_code]="LUNCH-OVER"))/60)
		lineageTag: 258d4e5d-504e-4da8-b664-3d4ae8566e75

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Break Over Hours' = (CALCULATE(SUM('Summed Process Report'[total_mins]),FILTER('Summed Process Report','Summed Process Report'[process_code]="BREAK-OVER"))/60)
		lineageTag: 91cbb3f8-7aef-4d5c-a4ee-85653c2c959b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column wh_id
		dataType: string
		lineageTag: 7f0a3b6a-45fe-4bc4-9afc-7b8690fb1b93
		summarizeBy: none
		sourceColumn: wh_id

		annotation SummarizationSetBy = Automatic

	column EmployeeName
		dataType: string
		lineageTag: ee91c759-db8a-45d6-bb67-91d75a108551
		summarizeBy: none
		sourceColumn: EmployeeName

		annotation SummarizationSetBy = Automatic

	column EmployeeNumber
		dataType: string
		lineageTag: 50c03a27-a4b8-40e9-ac34-faa066568f31
		summarizeBy: none
		sourceColumn: EmployeeNumber

		annotation SummarizationSetBy = Automatic

	column process_transaction
		dataType: string
		lineageTag: e3c7d629-a8fb-4860-8113-7525e424637b
		summarizeBy: none
		sourceColumn: process_transaction

		annotation SummarizationSetBy = Automatic

	column work_day
		dataType: dateTime
		formatString: General Date
		lineageTag: 0cfebe13-d32c-4fbb-973c-7d496b3e99d7
		summarizeBy: none
		sourceColumn: work_day

		variation Variation
			isDefault
			relationship: 00a63575-abb8-4922-8206-a3416c3727c9
			defaultHierarchy: LocalDateTable_d1f44691-daf3-4621-a930-8ff3a111e6e4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column total_mins
		dataType: double
		lineageTag: 2ae500af-6807-4e9f-812f-1691ca286c9c
		summarizeBy: sum
		sourceColumn: total_mins

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_transactions
		dataType: int64
		formatString: 0
		lineageTag: b5bfaee9-d814-49d3-9621-f52e258e1e93
		summarizeBy: sum
		sourceColumn: total_transactions

		annotation SummarizationSetBy = Automatic

	column Total_SAM_MINS
		dataType: double
		lineageTag: f5fbc1c3-16c6-44f7-bc14-2ab948fbb26a
		summarizeBy: sum
		sourceColumn: Total_SAM_MINS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column labor_type
		dataType: string
		lineageTag: b96659db-8c47-41a8-b20e-b3951b7ec177
		summarizeBy: none
		sourceColumn: labor_type

		annotation SummarizationSetBy = Automatic

	column process_start_min
		dataType: dateTime
		formatString: General Date
		lineageTag: b85f6c95-cdc8-431a-9e16-bf3e662b52e3
		summarizeBy: none
		sourceColumn: process_start_min

		variation Variation
			isDefault
			relationship: 745f661f-2ad4-464b-b272-fa8041086fd0
			defaultHierarchy: LocalDateTable_8d3e7a1f-0bb8-4cc1-b0d8-0754209fdb5f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column process_end_max
		dataType: dateTime
		formatString: General Date
		lineageTag: 5fcee232-d80f-446d-8431-2ebfc2c38a51
		summarizeBy: none
		sourceColumn: process_end_max

		variation Variation
			isDefault
			relationship: 53c8aabe-51a9-40b2-b913-5c493f671f5c
			defaultHierarchy: LocalDateTable_633f8970-8aa7-48e0-96d7-a94e985e9589.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column WhseEmployee
		dataType: string
		lineageTag: 0efbe36d-79cd-471c-b11c-22bcb940e323
		summarizeBy: none
		sourceColumn: WhseEmployee

		annotation SummarizationSetBy = Automatic

	column Flag
		dataType: string
		lineageTag: 6e2b7dcc-e43d-464e-86ff-d07439424036
		summarizeBy: none
		sourceColumn: Flag

		annotation SummarizationSetBy = Automatic

	column 'master key' = 'Summed Process Report'[WhseEmployee]&"-"&'Summed Process Report'[work_day]
		lineageTag: 895f9bb8-1328-46e8-b1dc-159f24ce1694
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column process_id
		dataType: string
		lineageTag: 39d1c7de-80f3-4dfc-9b11-8895255e2843
		summarizeBy: none
		sourceColumn: process_id

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column process_code
		dataType: string
		lineageTag: e1773a0d-5ca0-4e76-92aa-abc85f2d05c5
		summarizeBy: none
		sourceColumn: process_code

		annotation SummarizationSetBy = Automatic

	partition 'Summed Process Report' = m
		mode: import
		source =
				let
				    Source = Sql.Database("ashley-edw.database.windows.net", "ASHLEY_EDW", [Query="SELECT#(lf)     a.[wh_id]#(lf)    ,b.[EmployeeName]#(lf)    ,b.[EmployeeNumber]#(lf)    ,a.[process_transaction]#(lf)    ,CAST(a.[work_day] AS DATE)                              AS [work_day]#(lf)    ,COUNT(a.[process_id])                                   AS total_transactions#(lf)    ,SUM(a.[total_sam])                                      AS Total_SAM_MINS#(lf)    ,a.[labor_type]#(lf)    ,a.[process_id]#(lf)    ,c.process_code#(lf)    ,SUM(#(lf)        CASE#(lf)            WHEN c.process_code LIKE 'LUNCH-OVER%'#(lf)             AND DATEPART(HOUR, a.process_start) >= 7#(lf)             AND DATEPART(HOUR, a.process_start) <  16#(lf)            THEN CASE#(lf)                    WHEN a.actual_elapsed_time - 15 < 0 THEN 0#(lf)                    ELSE a.actual_elapsed_time - 15#(lf)                 END#(lf)            ELSE a.actual_elapsed_time#(lf)        END#(lf)     )                                                       AS total_mins#(lf)    ,MIN(a.process_start)                                    AS process_start_min#(lf)    ,MAX(a.process_end)                                      AS process_end_max#(lf)#(lf)FROM [Distribution_Warehouse_Wholesale].[ProcessReport]         a#(lf)    LEFT JOIN [PowerBI_Distribution].[DimEmployee]              b#(lf)           ON a.[employee_id]  = b.[EmployeeID]#(lf)          AND a.[wh_id]        = b.[WarehouseID]#(lf)    LEFT JOIN [Distribution_Warehouse_Wholesale].[t_la_process] c#(lf)           ON a.[process_id]   = c.[process_id]#(lf)          AND a.[wh_id]        = c.[wh_id]#(lf)#(lf)WHERE a.[wh_id] IN ('335','35')#(lf)  AND  a.[work_day]    >  DATEADD(DAY, -15, GETDATE())#(lf)  AND  a.[application] =  'WA'#(lf)#(lf)GROUP BY#(lf)     a.[wh_id]#(lf)    ,b.[EmployeeName]#(lf)    ,b.[EmployeeNumber]#(lf)    ,a.[process_transaction]#(lf)    ,CAST(a.[work_day] AS DATE)#(lf)    ,a.[labor_type]#(lf)    ,a.[process_id]#(lf)    ,c.[process_code]", CreateNavigationProperties=false, CommandTimeout=#duration(0, 2, 40, 0)]),
				    #"Added Custom" = Table.AddColumn(Source, "WhseEmployee", each [wh_id]&"-"&[EmployeeNumber]),
				    #"Added Conditional Column" = Table.AddColumn(#"Added Custom", "Flag", each if [wh_id] = "5" then "Yes" else if [wh_id] = "42" then "Yes" else "No")
				in
				    #"Added Conditional Column"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

