table Dim_Employee
	lineageTag: 6f64a92c-e372-4734-94b2-4ce4310603e6

	column Employee_ID
		dataType: string
		lineageTag: 0c0b0f9f-1ca5-4910-ba18-8d653f5c0f7c
		summarizeBy: none
		sourceColumn: Employee_ID

		annotation SummarizationSetBy = Automatic

	column Employee_Name
		dataType: string
		lineageTag: 294009c8-f910-4a15-a78f-23df6a85eb03
		summarizeBy: none
		sourceColumn: Employee_Name

		annotation SummarizationSetBy = Automatic

	partition Dim_Employee = m
		mode: import
		source =
				let
				    Source = Fct_Supervisors_Hours,
				    KeptCols = Table.SelectColumns(Source, {"Employee_ID","Name","Date"}),
				
				    // 数据类型（ID 一律用文本，防止丢前导零）
				    Typed = Table.TransformColumnTypes(
				        KeptCols,
				        {{"Employee_ID", type text}, {"Name", type text}, {"Date", type date}}
				    ),
				
				    // 去空格
				    Trimmed = Table.TransformColumns(
				        Typed,
				        {{"Employee_ID", Text.Trim, type text}, {"Name", Text.Trim, type text}}
				    ),
				
				    // 过滤无效值：空、"0"
				    FilteredID = Table.SelectRows(Trimmed, each [Employee_ID] <> null and [Employee_ID] <> "" and [Employee_ID] <> "0"),
				    FilteredName = Table.SelectRows(FilteredID, each [Name] <> null and [Name] <> "" and [Name] <> "0"),
				
				    // 按日期降序，确保最新名字排前面（可选）
				    Sorted = Table.Sort(FilteredName, {{"Date", Order.Descending}}),
				
				    // 分组：每个 Employee_ID 下把所有 Name 用逗号连接
				    Grouped = Table.Group(
				        Sorted,
				        {"Employee_ID"},
				        {
				            {"Employee_Name", each Text.Combine(List.Distinct([Name]), ", "), type text}
				        }
				    ),
				
				    // 按 ID 排序，美观
				    Final = Table.Sort(Grouped, {{"Employee_ID", Order.Ascending}})
				in
				    Final

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

