table Fct_metrics_goal
	lineageTag: e0d15fa8-fbf9-4ecf-8a86-ed7f46db45c1

	column MetricName
		dataType: string
		lineageTag: bbfdea25-9e6d-4387-9d17-002bdd7a8df6
		summarizeBy: none
		sourceColumn: MetricName

		annotation SummarizationSetBy = Automatic

	column Goal
		dataType: int64
		formatString: 0
		lineageTag: 47e66531-5762-4107-9faa-7aeee0211d02
		summarizeBy: none
		sourceColumn: Goal

		annotation SummarizationSetBy = Automatic

	partition Fct_metrics_goal = m
		mode: import
		source = ```
				let
				    // 连接 SharePoint 并筛选目标文件夹内的最新 .xlsx 文件
				    Source = SharePoint.Files("https://masterashley.sharepoint.com/sites/AsiaWarehouseOperations/", [ApiVersion = 15]),
				    FilteredFolder = Table.SelectRows(Source, each Text.StartsWith([Folder Path], "https://masterashley.sharepoint.com/sites/AsiaWarehouseOperations/Shared Documents/Power BI Source Files/") and Text.EndsWith([Name], ".xlsx")),
				    #"Filtered Rows" = Table.SelectRows(FilteredFolder, each ([Name] = "Wanek_PPH_Goal_Setup.xlsx")),
				    LatestFile = Table.SelectRows(#"Filtered Rows", each [Date created] = List.Max(#"Filtered Rows"[Date created])),
				    
				    // 读取 Excel 内容并展开指定工作表
				    ExcelData = Excel.Workbook(LatestFile{0}[Content]),
				    SheetData = Table.SelectRows(ExcelData, each [Item] = "Sheet1"){0}[Data],
				    
				    // 设置列名并转换数据类型
				    #"Promoted Headers" = Table.PromoteHeaders(SheetData, [PromoteAllScalars = true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Goal", Int64.Type}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

