table Query1
	lineageTag: 18624c9e-a5b0-434e-a1bc-6eeb60c4230c

	column LOCATION
		dataType: string
		lineageTag: 410ecaf8-3f9b-4e36-b369-d17eafa07c2c
		summarizeBy: none
		sourceColumn: LOCATION

		annotation SummarizationSetBy = Automatic

	column Building
		dataType: string
		lineageTag: a1251972-b037-4eba-b26e-86b03450ca37
		summarizeBy: none
		sourceColumn: Building

		annotation SummarizationSetBy = Automatic

	partition Query1 = m
		mode: import
		source =
				let
				    BaseUrl = "https://masterashley.sharepoint.com/sites/AsiaWarehouseOperations/MIL/",
				    FolderPath = BaseUrl & "Shared Documents/picking location/",
				
				    Source = SharePoint.Files(BaseUrl, [ApiVersion = 15]),
				
				    TargetFile = Table.SelectRows(Source, each [Folder Path] = FolderPath and [Name] = "Picking location.xlsx"),
				
				    Sheet1Data = Table.SelectRows(
				                    Table.ExpandTableColumn(
				                        Table.AddColumn(TargetFile, "wb", each Excel.Workbook([Content])),
				                        "wb", {"Data","Item"}, {"Data","Item"}
				                    ),
				                    each [Item] = "Sheet1")[Data]{0},
				
				    Result = Table.SelectColumns(
				                Table.PromoteHeaders(Sheet1Data, [PromoteAllScalars=true]),
				                {"LOCATION", "Building"})
				in
				    Result

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

